---
- name: EDA lab
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://localhost:8080/
        delay: 10
  rules:
    - name: Restart Wildfly if url is not reachable
      condition: event.url_check.status == "down"
      action:
        run_playbook:
          name: /home/cloud-user/wfly-remediation-with-eda/playbooks/restart_wildfly.yml
